services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crmdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always